{% set name = "seaduck" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/seaduck-{{ version }}.tar.gz
  sha256: 5f346f769a93fd1fc147ab66be3cc8e422884c48e9474fc6760ae33eef76ee67

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - scipy
    - dask-core
    - xarray

test:
  imports:
    - seaduck
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MaceKuailv/seaduck
  dev_url: https://github.com/MaceKuailv/seaduck
  doc_url: https://macekuailv.github.io/seaduck/
  summary: A python package that interpolates data from ocean dataset from both Eulerian and Lagrangian perspective.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MaceKuailv
